version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0

kos:
  - repositories:
      - ghcr.io/barakplasma/whatsmeow-transcribe
      # - ghcr.io/hoehermann/whatsmeow-transcribe
    tags:
      - "{{.Version}}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64


release:
  github:

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
